"""Writes one redirect page per short link in links.json: /<name>/index.html -> its target.
Run after editing links.json, then `python3 check.py` once GitHub Pages has published."""
import json, html, pathlib, shutil

ROOT = pathlib.Path(__file__).parent
PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Redirecting</title>
<meta name="robots" content="noindex">
<link rel="canonical" href="{t}">
<meta http-equiv="refresh" content="0; url={t}">
<script>location.replace({js} + location.hash)</script>
</head><body><p><a href="{t}">Continue</a></p></body></html>
"""

links = json.loads((ROOT / "links.json").read_text())
for name in [p.name for p in ROOT.iterdir() if p.is_dir() and (p / ".short-link").exists()]:
    if name not in links:
        shutil.rmtree(ROOT / name)  # a short link removed from links.json
for name, target in links.items():
    d = ROOT / name
    d.mkdir(exist_ok=True)
    (d / ".short-link").write_text("generated by build.py from links.json\n")
    (d / "index.html").write_text(PAGE.format(t=html.escape(target), js=json.dumps(target)))
print(f"wrote {len(links)} short links")
